packages:
  - "apps/*"
  - "modules/*"
  - "libs/*"
  - "utils/*"
  - "clis/*"
  - "plugins/*"
  - "databases/*"
allowBuilds:
  '@apollo/protobufjs': set this to true or false
  '@parcel/watcher': set this to true or false
  '@prisma/engines': set this to true or false
  '@scarf/scarf': set this to true or false
  '@swc/core': set this to true or false
  better-sqlite3: set this to true or false
  nx: set this to true or false
  prisma: set this to true or false
  unrs-resolver: set this to true or false
