packages:
  - "apps/*"
  - "modules/*"
  - "libs/*"
  - "utils/*"
  - "clis/*"
  - "plugins/*"

autoInstallPeers: true
allowBuilds:
  "@swc/core": true
  nx: true
  unrs-resolver: set this to true or false
